name: DevSecOps Compliance Pipeline

on: [push, pull_request]

jobs:
  # JOB 1: Secret Scanning
  secret-scanning:
    name: Secret Scanning (TruffleHog)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug